<a href="https://colab.research.google.com/github/alexchung8/sas-visualanalytics-thirdpartyvisualizations/blob/master/Exe_SQL_with_Python_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import requests
import pandas as pd
from pandasql import sqldf

In [15]:
file_path=r"/home_equity_py.csv"
url = r"https://support.sas.com/documentation/onlinedoc/viya/exampledatasets/hom_equity.csv"

In [16]:
response = requests.get(url)
with open(file_path, 'wb') as f:
  f.write(response.content)
  print(f'file download:{file_path}')

file download:/home_equity_py.csv

In [17]:
he_df = pd.read_csv(file_path)

In [18]:
he_df.head()

Empty DataFrame
Columns: [<h1>Not Found</h1>]
Index: []

In [13]:
sqldf('''
select * from he_df limit 10
''')

Empty DataFrame
Columns: [<h1>Not Found</h1>]
Index: []